# Generated by Django 4.2 on 2022-10-19 17:20

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=255, null=True)),
                ("titulo", models.CharField(max_length=255, null=True)),
                ("subtitulo", models.CharField(max_length=255, null=True)),
                (
                    "resumo",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "conteudo",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            10,
                            19,
                            17,
                            20,
                            29,
                            967824,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
