# Generated by Django 4.2 on 2022-10-10 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 10, 14, 52, 32, 78859)
            ),
        ),
    ]
