# Generated by Django 4.2 on 2022-10-19 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 19, 17, 20, 33, 625829, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
