# Generated by Django 4.2 on 2022-10-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_autor_post_conteudo_post_data_publicacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="autor",),
        migrations.RemoveField(model_name="post", name="conteudo",),
        migrations.RemoveField(model_name="post", name="data_publicacao",),
        migrations.RemoveField(model_name="post", name="resumo",),
        migrations.RemoveField(model_name="post", name="subtitulo",),
        migrations.RemoveField(model_name="post", name="titulo",),
    ]
