# Generated by Django 4.2 on 2022-10-19 17:51

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_autor_remove_post_conteudo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="autor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 19, 17, 51, 53, 32369, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="imagem_capa",
            field=models.ImageField(blank=True, null=True, upload_to="static/blog/"),
        ),
        migrations.AddField(
            model_name="post",
            name="resumo",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitulo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="titulo",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
